# Configuration for HalfCheetah with pixel observations

active_inference:
  env_name: "HalfCheetah-v4"
  action_dim: 6  # State dim will be encoder output
  
  # Active inference parameters
  precision_init: 1.0
  expected_free_energy_horizon: 3  # Shorter for pixels
  epistemic_weight: 0.2  # Higher for exploration
  extrinsic_weight: 0.8
  discount_factor: 0.99
  
  # Model architecture
  hidden_dim: 256
  latent_dim: 50
  num_layers: 3
  
  # Training
  batch_size: 128  # Smaller for memory
  learning_rate: 1e-4  # Lower for stability
  gradient_clip: 1.0
  
  # Diffusion
  diffusion:
    num_diffusion_steps: 50  # Fewer steps for speed
    beta_start: 1e-4
    beta_end: 0.02
    beta_schedule: "cosine"
    
  # Belief dynamics
  belief_dynamics:
    use_belief_dynamics: true
    diffusion_coefficient: 0.05  # Lower for stability
    learning_rate: 0.05
    dt: 0.01
    use_full_covariance: false

pixel:
  image_shape: [3, 84, 84]
  frame_stack: 3
  encoder_type: "drqv2"
  encoder_feature_dim: 50
  augmentation: true
  random_shift_pad: 4

training:
  total_timesteps: 2_000_000  # More steps for pixels
  eval_frequency: 20_000
  save_frequency: 100_000
  log_frequency: 1_000
  
  exploration_noise: 0.2  # Higher initial exploration
  exploration_decay: 0.995
  min_exploration: 0.05
  
  buffer_size: 100_000
  learning_starts: 10_000
  train_frequency: 1  # More frequent updates
  gradient_steps: 1
  
  num_eval_episodes: 10
  
  use_wandb: true
  project_name: "active-inference-diffusion"
  experiment_name: "halfcheetah_pixel_drqv2"

