"""
Policy Networks for Diffusion-Conditioned Active Inference
"""

import torch
import torch.nn as nn
import torch.distributions as dist
from typing import Optional, Tuple, List, Dict, Union, Literal
import math
import numpy as np  
import torch.nn.functional as F  
import torch.utils.checkpoint as cp
from torch.nn.attention import SDPBackend, sdpa_kernel
Tensor = torch.Tensor

# ---- Tanh-squash helpers -----------------------------------------------------

def tanh_squash(action_pre_tanh: Tensor) -> Tensor:
    return torch.tanh(action_pre_tanh)

def tanh_correction_logdet(a_t: Tensor, eps: float = 1e-6) -> Tensor:
    # log |det d tanh(u) / du| = sum_i log(1 - tanh(u_i)^2)
    return torch.log1p(-a_t.pow(2) + eps).sum(-1)

# ---- Initialization ----------------------------------------------------------

def initialize_policy_weights(module: nn.Module,
                              orthogonal_linear: bool = True,
                              final_std: float = 0.01) -> None:
    """
    Initialize Linear/Conv/LSTM/Transformer weights with sensible defaults.
    - MLP/LSTM: orthogonal (good for actors)
    - Transformer/GTrXL: Xavier for projections/FFN; keep defaults for MHA
    - Final policy heads: small gain
    """
    for m in module.modules():
        if isinstance(m, nn.Linear):
            if orthogonal_linear:
                nn.init.orthogonal_(m.weight)
            else:
                nn.init.xavier_uniform_(m.weight)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, (nn.Conv1d, nn.Conv2d)):
            nn.init.kaiming_uniform_(m.weight, a=math.sqrt(5))
            if m.bias is not None:
                fan_in, _ = nn.init._calculate_fan_in_and_fan_out(m.weight)
                bound = 1 / math.sqrt(fan_in) if fan_in > 0 else 0
                nn.init.uniform_(m.bias, -bound, bound)
        elif isinstance(m, nn.LSTM):
            for name, p in m.named_parameters():
                if "weight_ih" in name:
                    nn.init.xavier_uniform_(p)
                elif "weight_hh" in name:
                    nn.init.orthogonal_(p)
                elif "bias" in name:
                    nn.init.zeros_(p)
        elif isinstance(m, nn.MultiheadAttention):
            # Leave default init or apply Xavier if desired
            pass

    # Small final layers
    for m in module.modules():
        if isinstance(m, nn.Linear) and getattr(m, "_is_policy_final", False):
            if orthogonal_linear:
                nn.init.orthogonal_(m.weight, gain=final_std)
            else:
                nn.init.xavier_uniform_(m.weight)
            if m.bias is not None:
                nn.init.zeros_(m.bias)

class DiffusionConditionedPolicy(nn.Module):
    """
    Gaussian policy conditioned on diffusion-generated latents
    Implements: p_φ(π|z) = N(π; μ_φ(z), Σ_φ(z))
    
    Key innovation: Policies emerge from the continuous latent manifold
    generated by the diffusion process
    """
    
    def __init__(self,
                 latent_dim: int,
                 action_dim: int,
                 hidden_dim: int = 256,
                 num_layers: int = 2,
                 squash_output: bool = True,
                 state_dependent_std: bool = True,
                 min_std: float = 1e-4,
                 max_std: float = 1.0,
                 checkpoint: bool = True):
        super().__init__()
        self.squash_output = squash_output
        self.state_dependent_std = state_dependent_std
        self.min_std = min_std
        self.max_std = max_std
        self.checkpoint = bool(checkpoint)

        layers: List[nn.Module] = []
        in_dim = latent_dim
        for _ in range(num_layers):
            layers += [nn.Linear(in_dim, hidden_dim), nn.LayerNorm(hidden_dim), nn.ReLU(inplace=True)]
            in_dim = hidden_dim
        self.trunk = nn.Sequential(*layers)

        self.mean_head = nn.Linear(hidden_dim, action_dim); self.mean_head._is_policy_final = True
        if state_dependent_std:
            self.std_head = nn.Linear(hidden_dim, action_dim); self.std_head._is_policy_final = True
        else:
            self.log_std = nn.Parameter(torch.full((action_dim,), math.log(0.3)))

        initialize_policy_weights(self, orthogonal_linear=True)

    @staticmethod
    def _maybe_checkpoint(mod: nn.Module, x: Tensor, enabled: bool) -> Tensor:
        if enabled and isinstance(x, Tensor) and x.requires_grad:
            return cp.checkpoint(mod, x, use_reentrant=False)
        return mod(x)

    def forward(self,
                z: Tensor,
                deterministic: bool = False
                ) -> Tuple[Tensor, Tensor, dist.Distribution]:
        """
        Returns:
          action: [B, A], log_prob: [B], distribution object
        """
        h = self._maybe_checkpoint(self.trunk, z, self.checkpoint)

        mean = self.mean_head(h)
        if self.state_dependent_std:
            std = torch.clamp(self.std_head(h).exp(), self.min_std, self.max_std)
        else:
            std = torch.clamp(self.log_std.exp(), self.min_std, self.max_std)

        base = dist.Normal(mean, std)
        u = mean if deterministic else base.rsample()

        if self.squash_output:
            a = torch.tanh(u)
            log_prob = base.log_prob(u).sum(-1) - torch.log1p(-a.pow(2) + 1e-6).sum(-1)
            dist_out = dist.TransformedDistribution(base, [torch.distributions.transforms.TanhTransform(cache_size=0)])
            return a, log_prob, dist_out
        else:
            log_prob = base.log_prob(u).sum(-1)
            return u, log_prob, base
        
    def get_policy_entropy(self, z: torch.Tensor) -> torch.Tensor:
        """Compute policy entropy for exploration bonus"""
        _, _, distribution = self.forward(z, deterministic=True)
        dist = getattr(distribution, "base_dist", distribution)
        return dist.entropy().sum(dim=-1)



class LSTMTemporalEncoder(nn.Module):
    """
    One-step LSTM encoder with done-based resets.
    Input: x_t [B,D], state (h,c) with [L,B,H], done [B]
    Output: y_t [B,H], new_state
    """
    def __init__(self, dim: int, hidden_dim: int = 256, num_layers: int = 1, checkpoint: bool = False):
        super().__init__()
        self.lstm = nn.LSTM(dim, hidden_dim, num_layers=num_layers, batch_first=True)
        self.checkpoint = bool(checkpoint)
        initialize_policy_weights(self, orthogonal_linear=True)

    def initial_state(self, batch_size: int, device: torch.device) -> Tuple[Tensor, Tensor]:
        h = torch.zeros(self.lstm.num_layers, batch_size, self.lstm.hidden_size, device=device)
        c = torch.zeros_like(h)
        return h, c

    def forward(self, x_t: Tensor, state: Optional[Tuple[Tensor, Tensor]], done: Optional[Tensor] = None
                ) -> Tuple[Tensor, Tuple[Tensor, Tensor]]:
        B = x_t.size(0)
        if state is None:
            state = self.initial_state(B, x_t.device)

        if done is not None:
            dm = done.view(1, -1, 1).to(state[0].dtype)
            h0 = state[0] * (1.0 - dm)
            c0 = state[1] * (1.0 - dm)
            state = (h0, c0)

        x = x_t.unsqueeze(1)  # [B,1,D]
        if self.checkpoint and x.requires_grad:
            y, new_state = cp.checkpoint(self.lstm, x, state, use_reentrant=False)  # type: ignore[arg-type]
        else:
            y, new_state = self.lstm(x, state)
        return y.squeeze(1), new_state

# ---- Mask utilities ----------------------------------------------------------

def causal_square_mask(T: int, device, dtype=torch.float32) -> Tensor:
    # Additive mask with -inf above diagonal, 0 elsewhere. Shape [T,T]
    m = torch.full((T, T), float('-inf'), device=device, dtype=dtype)
    m = torch.triu(m, diagonal=1)
    m = m.masked_fill(torch.tril(torch.ones(T, T, device=device, dtype=torch.bool)) , 0.0)
    return m

def done_causal_mask(done: Tensor) -> Tensor:
    """
    Build additive mask [T,T] for a *single* sequence done flags [T].
    - Causal (no attending to future)
    - Disallow attention across episode boundaries (segments split by done==1)
    """
    T = done.numel()
    device = done.device
    dtype = torch.float32
    # causal
    mask = causal_square_mask(T, device, dtype=dtype)  # [T,T] with -inf above diag
    # build segment ids; done marks terminal at that step
    seg = done.cumsum(dim=0)  # [T]
    seg_i = seg.view(T, 1).expand(T, T)
    seg_j = seg.view(1, T).expand(T, T)
    cross = seg_i.ne(seg_j)  # True when across segments
    mask = torch.where(cross, torch.tensor(float('-inf'), device=device, dtype=dtype), mask)
    return mask

# ---- Transformer temporal encoder (windowed, masked) -------------------------

class TemporalTransformer(nn.Module):
    """
    Windowed TransformerEncoder with optional done-aware masking.

    Modes:
      - shared_mask (default): reduce per-sample masks across batch to a single [T,T] mask
        using method='union' (any boundary blocks) or 'mean' (thresholded average).
      - strict_per_sample: loop over batch and apply exact per-sample masks.

    Returns the encoded last token.
    """
    def __init__(self, dim: int, n_layers: int = 2, n_heads: int = 4, ff_mult: int = 4,
                 dropout: float = 0.1, checkpoint: bool = False,
                 strict_per_sample: bool = False,
                 reduction: Literal["union", "mean"] = "union",
                 mean_threshold: float = 0.5):
        super().__init__()
        self.layers = nn.ModuleList([
            nn.TransformerEncoderLayer(d_model=dim, nhead=n_heads,
                                       dim_feedforward=dim * ff_mult,
                                       dropout=dropout, batch_first=True,
                                       activation="gelu", norm_first=True)
            for _ in range(n_layers)
        ])
        self.pos_emb = nn.Parameter(torch.randn(1, 512, dim) * 0.01)  # max T=512
        self.checkpoint = bool(checkpoint)
        self.strict_per_sample = bool(strict_per_sample)
        self.reduction = reduction
        self.mean_threshold = float(mean_threshold)
        # Xavier for transformer-style layers
        initialize_policy_weights(self, orthogonal_linear=False)

    def _reduce_masks(self, masks_bt: Tensor) -> Tensor:
        # masks_bt: [B, T, T] additive (-inf or 0). Reduce to [T, T].
        if self.reduction == "union":
            m = torch.isneginf(masks_bt)  # True where -inf
            m = m.any(dim=0)              # [T,T] union across batch
            out = torch.where(m, torch.tensor(float('-inf'), device=masks_bt.device), torch.tensor(0.0, device=masks_bt.device))
        else:
            # "mean": average then threshold
            # convert to 1 for -inf, 0 for 0
            bmask = torch.isneginf(masks_bt).float()
            avg = bmask.mean(dim=0)
            out = torch.where(avg >= self.mean_threshold,
                              torch.tensor(float('-inf'), device=masks_bt.device),
                              torch.tensor(0.0, device=masks_bt.device))
        return out  # [T,T]

    def forward(self, z_seq: Tensor, done_seq: Optional[Tensor] = None) -> Tensor:
        """
        z_seq: [B, T, D], done_seq: [B, T] with 1 at terminal steps
        """
        B, T, D = z_seq.shape
        pos = self.pos_emb[:, :T, :]
        x = z_seq + pos

        if done_seq is None:
            attn_mask = causal_square_mask(T, x.device, dtype=torch.float32)  # [T,T]
            for layer in self.layers:
                if self.checkpoint and x.requires_grad:
                    x = cp.checkpoint(lambda _x, m=attn_mask: layer(_x, src_mask=m), x, use_reentrant=False)
                else:
                    x = layer(x, src_mask=attn_mask)
            return x[:, -1, :]

        # done-aware
        if self.strict_per_sample:
            outs = []
            for b in range(B):
                m = done_causal_mask(done_seq[b])  # [T,T]
                x_b = x[b:b+1, :, :]
                for layer in self.layers:
                    if self.checkpoint and x_b.requires_grad:
                        x_b = cp.checkpoint(lambda _x, mm=m: layer(_x, src_mask=mm), x_b, use_reentrant=False)
                    else:
                        x_b = layer(x_b, src_mask=m)
                outs.append(x_b[:, -1, :])  # [1,D]
            return torch.cat(outs, dim=0)  # [B,D]
        else:
            masks = torch.stack([done_causal_mask(done_seq[b]) for b in range(B)], dim=0)  # [B,T,T]
            attn_mask = self._reduce_masks(masks)  # [T,T]
            for layer in self.layers:
                if self.checkpoint and x.requires_grad:
                    x = cp.checkpoint(lambda _x, m=attn_mask: layer(_x, src_mask=m), x, use_reentrant=False)
                else:
                    x = layer(x, src_mask=attn_mask)
            return x[:, -1, :]

# ---- GTrXL-style gated Transformer ------------------------------------------

class GRUGate(nn.Module):
    def __init__(self, dim: int):
        super().__init__()
        self.Wr = nn.Linear(dim, dim)
        self.Ur = nn.Linear(dim, dim, bias=False)
        self.Wz = nn.Linear(dim, dim)
        self.Uz = nn.Linear(dim, dim, bias=False)
        self.Wg = nn.Linear(dim, dim)
        self.Ug = nn.Linear(dim, dim, bias=False)

    def forward(self, x: Tensor, y: Tensor) -> Tensor:
        r = torch.sigmoid(self.Wr(y) + self.Ur(x))
        z = torch.sigmoid(self.Wz(y) + self.Uz(x))
        g = torch.tanh(self.Wg(y) + self.Ug(r * x))
        return (1 - z) * x + z * g

class GTrXLBlock(nn.Module):
    def __init__(self, dim: int, n_heads: int = 4, ff_mult: int = 4, dropout: float = 0.1):
        super().__init__()
        self.ln1 = nn.LayerNorm(dim)
        self.attn = nn.MultiheadAttention(dim, n_heads, dropout=dropout, batch_first=True)
        self.gate1 = GRUGate(dim)

        self.ln2 = nn.LayerNorm(dim)
        self.ff = nn.Sequential(
            nn.Linear(dim, dim * ff_mult),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(dim * ff_mult, dim),
            nn.Dropout(dropout),
        )
        self.gate2 = GRUGate(dim)

    def forward(self, x: Tensor, attn_mask: Optional[Tensor] = None, key_padding_mask: Optional[Tensor] = None) -> Tensor:
        # Pre-norm + masked attention
        y = self.ln1(x)
        with sdpa_kernel(SDPBackend.MATH):
            y, _ = self.attn(y, y, y, attn_mask=attn_mask, key_padding_mask=key_padding_mask, need_weights=False)
        x = self.gate1(x, y)
        # Pre-norm + FFN with gating
        y = self.ln2(x)
        y = self.ff(y)
        x = self.gate2(x, y)
        return x

class GTrXLTransformer(nn.Module):
    """
    Windowed GTrXL encoder with done-aware masking.
    Returns encoded last token.
    """
    def __init__(self, dim: int, n_layers: int = 2, n_heads: int = 4, ff_mult: int = 4,
                 dropout: float = 0.1, checkpoint: bool = False,
                 strict_per_sample: bool = False,
                 reduction: Literal["union", "mean"] = "union",
                 mean_threshold: float = 0.5):
        super().__init__()
        self.layers = nn.ModuleList([GTrXLBlock(dim, n_heads, ff_mult, dropout) for _ in range(n_layers)])
        self.pos_emb = nn.Parameter(torch.randn(1, 512, dim) * 0.01)
        self.checkpoint = bool(checkpoint)
        self.strict_per_sample = bool(strict_per_sample)
        self.reduction = reduction
        self.mean_threshold = float(mean_threshold)
        initialize_policy_weights(self, orthogonal_linear=False)

    def _reduce_masks(self, masks_bt: Tensor) -> Tensor:
        # Same reduction as TemporalTransformer
        if self.reduction == "union":
            m = torch.isneginf(masks_bt).any(dim=0)
            out = torch.where(m, torch.tensor(float('-inf'), device=masks_bt.device), torch.tensor(0.0, device=masks_bt.device))
        else:
            bmask = torch.isneginf(masks_bt).float()
            avg = bmask.mean(dim=0)
            out = torch.where(avg >= self.mean_threshold,
                              torch.tensor(float('-inf'), device=masks_bt.device),
                              torch.tensor(0.0, device=masks_bt.device))
        return out

    def forward(self, z_seq: Tensor, done_seq: Optional[Tensor] = None) -> Tensor:
        B, T, D = z_seq.shape
        x = z_seq + self.pos_emb[:, :T, :]

        if done_seq is None:
            m = causal_square_mask(T, x.device, dtype=torch.float32)  # [T,T]
            for layer in self.layers:
                if self.checkpoint and x.requires_grad:
                    x = cp.checkpoint(lambda _x, mm=m: layer(_x, attn_mask=mm, key_padding_mask=None), x, use_reentrant=False)
                else:
                    x = layer(x, attn_mask=m, key_padding_mask=None)
            return x[:, -1, :]

        if self.strict_per_sample:
            outs = []
            for b in range(B):
                m = done_causal_mask(done_seq[b])  # [T,T]
                x_b = x[b:b+1, :, :]
                for layer in self.layers:
                    if self.checkpoint and x_b.requires_grad:
                        x_b = cp.checkpoint(lambda _x, mm=m: layer(_x, attn_mask=mm, key_padding_mask=None), x_b, use_reentrant=False)
                    else:
                        x_b = layer(x_b, attn_mask=m, key_padding_mask=None)
                outs.append(x_b[:, -1, :])
            return torch.cat(outs, dim=0)
        else:
            masks = torch.stack([done_causal_mask(done_seq[b]) for b in range(B)], dim=0)  # [B,T,T]
            m = self._reduce_masks(masks)  # [T,T]
            for layer in self.layers:
                if self.checkpoint and x.requires_grad:
                    x = cp.checkpoint(lambda _x, mm=m: layer(_x, attn_mask=mm, key_padding_mask=None), x, use_reentrant=False)
                else:
                    x = layer(x, attn_mask=m, key_padding_mask=None)
            return x[:, -1, :]


class HierarchicalDiffusionPolicy(nn.Module):
    """
    Stacks multiple policy heads, each optionally preceded by a temporal encoder.
    At each level i:
      z_i = temporal_enc[i](z_{i-1}, state_i, done)  (identity if None)
      a_i ~ policy_i(z_i)
      z_{i} := a_i for next level (subgoal conditioning)
    Final action comes from the last level.
    """
    def __init__(self,
                 levels: int,
                 latent_dim: int,
                 action_dim: int,
                 hidden_dim: int = 256,
                 temporal: str = "none",     # "none" | "lstm" | "transformer" | "gtrxl"
                 temporal_dim: Optional[int] = None,
                 temporal_layers: int = 1,
                 temporal_heads: int = 4,
                 temporal_ff_mult: int = 4,
                 temporal_dropout: float = 0.1,
                 window: int = 16,           # for transformer/gtrxl (context length)
                 checkpoint_temporal: bool = False,
                 checkpoint_policy: bool = False,
                 squash_output: bool = True,
                 state_dependent_std: bool = True,
                 strict_done_mask: bool = False,
                 mask_reduction: Literal["union", "mean"] = "union",
                 mean_threshold: float = 0.5):
        super().__init__()
        self.levels = levels
        self.temporal = temporal
        self.window = window

        pols = []
        temps = []
        for _ in range(levels):
            # temporal encoder
            if temporal == "lstm":
                dim = temporal_dim or latent_dim
                temps.append(LSTMTemporalEncoder(latent_dim, hidden_dim=dim, num_layers=temporal_layers,
                                                 checkpoint=checkpoint_temporal))
                head_in = dim
            elif temporal == "transformer":
                temps.append(TemporalTransformer(dim=latent_dim, n_layers=temporal_layers,
                                                 n_heads=temporal_heads, ff_mult=temporal_ff_mult,
                                                 dropout=temporal_dropout, checkpoint=checkpoint_temporal,
                                                 strict_per_sample=strict_done_mask,
                                                 reduction=mask_reduction,
                                                 mean_threshold=mean_threshold))
                head_in = latent_dim
            elif temporal == "gtrxl":
                temps.append(GTrXLTransformer(dim=latent_dim, n_layers=temporal_layers,
                                              n_heads=temporal_heads, ff_mult=temporal_ff_mult,
                                              dropout=temporal_dropout, checkpoint=checkpoint_temporal,
                                              strict_per_sample=strict_done_mask,
                                              reduction=mask_reduction,
                                              mean_threshold=mean_threshold))
                head_in = latent_dim
            else:
                temps.append(None)
                head_in = latent_dim

            pol = DiffusionConditionedPolicy(latent_dim=head_in, action_dim=action_dim,
                                             hidden_dim=hidden_dim, num_layers=2,
                                             squash_output=squash_output,
                                             state_dependent_std=state_dependent_std,
                                             checkpoint=checkpoint_policy)
            pols.append(pol)

        self.policies = nn.ModuleList(pols)
        self.temporal_encoders = nn.ModuleList([t if t is not None else nn.Identity() for t in temps])

    def initial_state(self, batch_size: int, device: torch.device):
        states: List[Optional[Tuple[Tensor, Tensor]]] = []
        for t in self.temporal_encoders:
            if isinstance(t, LSTMTemporalEncoder):
                states.append(t.initial_state(batch_size, device))
            else:
                states.append(None)
        return states

    def forward(self,
                z: Tensor,
                hidden_states: Optional[List[Optional[Tuple[Tensor, Tensor]]]] = None,
                done: Optional[Tensor] = None,
                z_context: Optional[Tensor] = None,
                done_context: Optional[Tensor] = None,
                deterministic: bool = False
                ) -> Tuple[Tensor, Tensor, List[Optional[Tuple[Tensor, Tensor]]]]:
        """
        z: [B, Dz] current latent
        hidden_states: per-level states (only for LSTM)
        done: [B] flags to reset LSTM states
        z_context: [B, T, Dz] optional context for attention models; if None, uses single token
        done_context: [B, T] done flags for mask building
        """
        B = z.size(0)
        if hidden_states is None:
            hidden_states = self.initial_state(B, z.device)

        current = z
        new_states: List[Optional[Tuple[Tensor, Tensor]]] = []

        for lvl in range(self.levels):
            enc = self.temporal_encoders[lvl]

            if isinstance(enc, LSTMTemporalEncoder):
                y, new_state = enc(current, hidden_states[lvl], done)
                new_states.append(new_state)
                feat = y
            elif isinstance(enc, (TemporalTransformer, GTrXLTransformer)):
                if z_context is None:
                    ctx = current.unsqueeze(1)  # [B,1,D]
                    dctx = done.view(B, 1) if done is not None else None
                else:
                    ctx = z_context[:, -self.window:, :]
                    dctx = done_context[:, -self.window:] if (done_context is not None) else None
                feat = enc(ctx, dctx)
                new_states.append(None)
            else:
                feat = current
                new_states.append(None)

            action, logp, _ = self.policies[lvl](feat, deterministic=deterministic)
            current = action  # chain subgoals

        return action, logp, new_states